"""source grounded discovery and geological interpretation

Revision ID: 0004_discovery
Revises: 0003_ufvp_specimens
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0004_discovery"
down_revision: str | Sequence[str] | None = "0003_ufvp_specimens"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("""
        CREATE FUNCTION discovery_uuid(text) RETURNS uuid LANGUAGE sql IMMUTABLE STRICT
        PARALLEL SAFE AS $$ SELECT overlay(overlay(md5($1) placing '4' from 13 for 1)
            placing '8' from 17 for 1)::uuid $$
        """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "geological_interval",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("rank", sa.Text(), nullable=False),
        sa.Column("parent_id", sa.Text(), nullable=True),
        sa.Column("older_ma", sa.Numeric(), nullable=False),
        sa.Column("younger_ma", sa.Numeric(), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.Column("reference", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "older_ma >= younger_ma AND younger_ma >= 0", name=op.f("ck_geological_interval_bounds")
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["geological_interval.id"],
            name=op.f("fk_geological_interval_parent_id_geological_interval"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_geological_interval")),
    )
    op.create_table(
        "context_term",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_dataset_id", sa.Uuid(), nullable=False),
        sa.Column("field", sa.Text(), nullable=False),
        sa.Column("namespace", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("search_text", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_dataset_id"],
            ["source_dataset.id"],
            name=op.f("fk_context_term_source_dataset_id_source_dataset"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_context_term")),
    )
    op.create_index(
        "ix_context_term_search",
        "context_term",
        ["search_text"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"search_text": "gin_trgm_ops"},
    )
    op.create_table(
        "taxon_path",
        sa.Column("taxon_id", sa.Uuid(), nullable=False),
        sa.Column("ancestor_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ancestor_id"], ["taxon.id"], name=op.f("fk_taxon_path_ancestor_id_taxon")
        ),
        sa.ForeignKeyConstraint(
            ["taxon_id"], ["taxon.id"], name=op.f("fk_taxon_path_taxon_id_taxon")
        ),
        sa.PrimaryKeyConstraint("taxon_id", "ancestor_id", name=op.f("pk_taxon_path")),
    )
    op.create_index(op.f("ix_taxon_path_ancestor_id"), "taxon_path", ["ancestor_id"], unique=False)
    op.create_table(
        "age_interpretation",
        sa.Column("source_record_id", sa.Uuid(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("policy_version", sa.Text(), nullable=False),
        sa.Column("interval_id", sa.Text(), nullable=True),
        sa.Column("source_field", sa.Text(), nullable=True),
        sa.Column("source_label", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("rule", sa.Text(), nullable=False),
        sa.Column("older_ma", sa.Numeric(), nullable=True),
        sa.Column("younger_ma", sa.Numeric(), nullable=True),
        sa.Column(
            "interpreted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'mapped' AND interval_id IS NOT NULL AND older_ma IS NOT NULL "
            "AND younger_ma IS NOT NULL) OR (status <> 'mapped' AND interval_id IS NULL "
            "AND older_ma IS NULL AND younger_ma IS NULL)",
            name=op.f("ck_age_interpretation_mapping"),
        ),
        sa.CheckConstraint(
            "status IN ('mapped', 'ambiguous', 'unmapped', 'absent')",
            name=op.f("ck_age_interpretation_status"),
        ),
        sa.CheckConstraint(
            "older_ma >= younger_ma AND younger_ma >= 0", name=op.f("ck_age_interpretation_bounds")
        ),
        sa.ForeignKeyConstraint(
            ["interval_id"],
            ["geological_interval.id"],
            name=op.f("fk_age_interpretation_interval_id_geological_interval"),
        ),
        sa.ForeignKeyConstraint(
            ["source_record_id", "content_hash"],
            ["source_record_revision.source_record_id", "source_record_revision.content_hash"],
            name=op.f("fk_age_interpretation_source_record_id_source_record_revision"),
        ),
        sa.PrimaryKeyConstraint(
            "source_record_id", "content_hash", "policy_version", name=op.f("pk_age_interpretation")
        ),
    )
    op.create_table(
        "catalog_entry",
        sa.Column("occurrence_id", sa.Uuid(), nullable=False),
        sa.Column("specimen_id", sa.Uuid(), nullable=False),
        sa.Column("taxon_id", sa.Uuid(), nullable=False),
        sa.Column("locality_id", sa.Uuid(), nullable=True),
        sa.Column("collection_id", sa.Uuid(), nullable=True),
        sa.Column("institution_id", sa.Uuid(), nullable=True),
        sa.Column("source_record_id", sa.Uuid(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("policy_version", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("scientific_name", sa.Text(), nullable=False),
        sa.Column("search_text", sa.Text(), nullable=False),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('simple'::regconfig, search_text)", persisted=True),
            nullable=False,
        ),
        sa.Column("older_ma", sa.Numeric(), nullable=True),
        sa.Column("younger_ma", sa.Numeric(), nullable=True),
        sa.Column("age_basis", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collection.id"],
            name=op.f("fk_catalog_entry_collection_id_collection"),
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institution.id"],
            name=op.f("fk_catalog_entry_institution_id_institution"),
        ),
        sa.ForeignKeyConstraint(
            ["locality_id"], ["locality.id"], name=op.f("fk_catalog_entry_locality_id_locality")
        ),
        sa.ForeignKeyConstraint(
            ["occurrence_id"],
            ["occurrence.id"],
            name=op.f("fk_catalog_entry_occurrence_id_occurrence"),
        ),
        sa.ForeignKeyConstraint(
            ["source_record_id", "content_hash", "policy_version"],
            [
                "age_interpretation.source_record_id",
                "age_interpretation.content_hash",
                "age_interpretation.policy_version",
            ],
            name=op.f("fk_catalog_entry_source_record_id_age_interpretation"),
        ),
        sa.ForeignKeyConstraint(
            ["source_record_id"],
            ["source_record.id"],
            name=op.f("fk_catalog_entry_source_record_id_source_record"),
        ),
        sa.ForeignKeyConstraint(
            ["specimen_id"], ["specimen.id"], name=op.f("fk_catalog_entry_specimen_id_specimen")
        ),
        sa.ForeignKeyConstraint(
            ["taxon_id"], ["taxon.id"], name=op.f("fk_catalog_entry_taxon_id_taxon")
        ),
        sa.PrimaryKeyConstraint("occurrence_id", name=op.f("pk_catalog_entry")),
        sa.UniqueConstraint("source_record_id", name=op.f("uq_catalog_entry_source_record_id")),
    )
    op.create_index(
        "ix_catalog_entry_age", "catalog_entry", ["older_ma", "younger_ma"], unique=False
    )
    op.create_index(
        op.f("ix_catalog_entry_collection_id"), "catalog_entry", ["collection_id"], unique=False
    )
    op.create_index(
        op.f("ix_catalog_entry_institution_id"), "catalog_entry", ["institution_id"], unique=False
    )
    op.create_index(
        "ix_catalog_entry_label",
        "catalog_entry",
        ["label"],
        unique=False,
        postgresql_ops={"label": "text_pattern_ops"},
    )
    op.create_index(
        op.f("ix_catalog_entry_locality_id"), "catalog_entry", ["locality_id"], unique=False
    )
    op.create_index(
        "ix_catalog_entry_search_text",
        "catalog_entry",
        ["search_text"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"search_text": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_catalog_entry_search_vector",
        "catalog_entry",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_catalog_entry_specimen_id"), "catalog_entry", ["specimen_id"], unique=False
    )
    op.create_index(op.f("ix_catalog_entry_taxon_id"), "catalog_entry", ["taxon_id"], unique=False)
    op.create_table(
        "catalog_term",
        sa.Column("occurrence_id", sa.Uuid(), nullable=False),
        sa.Column("term_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["occurrence_id"],
            ["catalog_entry.occurrence_id"],
            name=op.f("fk_catalog_term_occurrence_id_catalog_entry"),
        ),
        sa.ForeignKeyConstraint(
            ["term_id"], ["context_term.id"], name=op.f("fk_catalog_term_term_id_context_term")
        ),
        sa.PrimaryKeyConstraint("occurrence_id", "term_id", name=op.f("pk_catalog_term")),
    )
    op.create_index(op.f("ix_catalog_term_term_id"), "catalog_term", ["term_id"], unique=False)
    op.add_column("taxon", sa.Column("source_dataset_id", sa.Uuid(), nullable=True))
    op.add_column("taxon", sa.Column("parent_taxon_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_taxon_parent_taxon_id"), "taxon", ["parent_taxon_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_taxon_parent_taxon_id_taxon"), "taxon", "taxon", ["parent_taxon_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_taxon_source_dataset_id_source_dataset"),
        "taxon",
        "source_dataset",
        ["source_dataset_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP FUNCTION IF EXISTS discovery_uuid(text)")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_taxon_source_dataset_id_source_dataset"), "taxon", type_="foreignkey"
    )
    op.drop_constraint(op.f("fk_taxon_parent_taxon_id_taxon"), "taxon", type_="foreignkey")
    op.drop_index(op.f("ix_taxon_parent_taxon_id"), table_name="taxon")
    op.drop_column("taxon", "parent_taxon_id")
    op.drop_column("taxon", "source_dataset_id")
    op.drop_index(op.f("ix_catalog_term_term_id"), table_name="catalog_term")
    op.drop_table("catalog_term")
    op.drop_index(op.f("ix_catalog_entry_taxon_id"), table_name="catalog_entry")
    op.drop_index(op.f("ix_catalog_entry_specimen_id"), table_name="catalog_entry")
    op.drop_index(
        "ix_catalog_entry_search_vector", table_name="catalog_entry", postgresql_using="gin"
    )
    op.drop_index(
        "ix_catalog_entry_search_text",
        table_name="catalog_entry",
        postgresql_using="gin",
        postgresql_ops={"search_text": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_catalog_entry_locality_id"), table_name="catalog_entry")
    op.drop_index(
        "ix_catalog_entry_label",
        table_name="catalog_entry",
        postgresql_ops={"label": "text_pattern_ops"},
    )
    op.drop_index(op.f("ix_catalog_entry_institution_id"), table_name="catalog_entry")
    op.drop_index(op.f("ix_catalog_entry_collection_id"), table_name="catalog_entry")
    op.drop_index("ix_catalog_entry_age", table_name="catalog_entry")
    op.drop_table("catalog_entry")
    op.drop_table("age_interpretation")
    op.drop_index(op.f("ix_taxon_path_ancestor_id"), table_name="taxon_path")
    op.drop_table("taxon_path")
    op.drop_index(
        "ix_context_term_search",
        table_name="context_term",
        postgresql_using="gin",
        postgresql_ops={"search_text": "gin_trgm_ops"},
    )
    op.drop_table("context_term")
    op.drop_table("geological_interval")
    # ### end Alembic commands ###
