"""retain additional reversible material reconciliation evidence

Revision ID: 0011_reconciliation
Revises: 0010_pbdb_evidence
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0011_reconciliation"
down_revision: str | Sequence[str] | None = "0010_pbdb_evidence"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reconciliation_generation",
        sa.Column("subject_dataset_id", sa.Uuid(), nullable=False),
        sa.Column("target_dataset_id", sa.Uuid(), nullable=False),
        sa.Column("policy_version", sa.Text(), nullable=False),
        sa.Column("input_digest", sa.String(length=64), nullable=False),
        sa.Column("source_state", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "published_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "subject_dataset_id <> target_dataset_id",
            name=op.f("ck_reconciliation_generation_independent_sources"),
        ),
        sa.ForeignKeyConstraint(
            ["subject_dataset_id"],
            ["source_dataset.id"],
            name=op.f("fk_reconciliation_generation_subject_dataset_id_source_dataset"),
        ),
        sa.ForeignKeyConstraint(
            ["target_dataset_id"],
            ["source_dataset.id"],
            name=op.f("fk_reconciliation_generation_target_dataset_id_source_dataset"),
        ),
        sa.PrimaryKeyConstraint(
            "subject_dataset_id",
            "target_dataset_id",
            "policy_version",
            name=op.f("pk_reconciliation_generation"),
        ),
    )
    op.create_table(
        "reconciliation_assessment",
        sa.Column("subject_dataset_id", sa.Uuid(), nullable=False),
        sa.Column("target_dataset_id", sa.Uuid(), nullable=False),
        sa.Column("source_record_id", sa.Uuid(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("normalization_hash", sa.String(length=64), nullable=False),
        sa.Column("occurrence_id", sa.Uuid(), nullable=True),
        sa.Column("policy_version", sa.Text(), nullable=False),
        sa.Column("input_digest", sa.String(length=64), nullable=False),
        sa.Column("creation_method", sa.Text(), server_default="automatic", nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("normalized_identifier", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("original_values", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "creation_method IN ('automatic','manual')",
            name=op.f("ck_reconciliation_assessment_creation_method"),
        ),
        sa.CheckConstraint(
            "status IN ('deterministic','candidate','ambiguous',"
            "'conflict','unresolved','rejected')",
            name=op.f("ck_reconciliation_assessment_status"),
        ),
        sa.CheckConstraint(
            "subject_dataset_id <> target_dataset_id",
            name=op.f("ck_reconciliation_assessment_independent_sources"),
        ),
        sa.ForeignKeyConstraint(
            ["occurrence_id"],
            ["occurrence.id"],
            name=op.f("fk_reconciliation_assessment_occurrence_id_occurrence"),
        ),
        sa.ForeignKeyConstraint(
            ["source_record_id", "content_hash", "normalization_hash"],
            [
                "normalized_source_revision.source_record_id",
                "normalized_source_revision.content_hash",
                "normalized_source_revision.normalization_hash",
            ],
            name=op.f("fk_reconciliation_assessment_source_record_id_normalized_source_revision"),
        ),
        sa.ForeignKeyConstraint(
            ["subject_dataset_id"],
            ["source_dataset.id"],
            name=op.f("fk_reconciliation_assessment_subject_dataset_id_source_dataset"),
        ),
        sa.ForeignKeyConstraint(
            ["target_dataset_id"],
            ["source_dataset.id"],
            name=op.f("fk_reconciliation_assessment_target_dataset_id_source_dataset"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reconciliation_assessment")),
        sa.UniqueConstraint(
            "source_record_id",
            "content_hash",
            "normalization_hash",
            "target_dataset_id",
            "policy_version",
            "input_digest",
            name="uq_reconciliation_assessment_frame",
        ),
    )
    op.create_index(
        "ix_reconciliation_assessment_generation",
        "reconciliation_assessment",
        ["subject_dataset_id", "target_dataset_id", "policy_version", "input_digest"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reconciliation_assessment_source_record_id"),
        "reconciliation_assessment",
        ["source_record_id"],
        unique=False,
    )
    op.create_table(
        "reconciliation_edge",
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("target_specimen_id", sa.Uuid(), nullable=False),
        sa.Column("target_source_record_id", sa.Uuid(), nullable=False),
        sa.Column("target_content_hash", sa.String(length=64), nullable=False),
        sa.Column("relationship_type", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("diagnostics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("supporting_reference_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(relationship_type='material_identifier_matches' AND status='deterministic') OR "
            "(relationship_type='candidate_same_specimen' AND status IN ('candidate','ambiguous'))",
            name=op.f("ck_reconciliation_edge_type_status"),
        ),
        sa.CheckConstraint(
            "relationship_type IN ('material_identifier_matches','candidate_same_specimen')",
            name=op.f("ck_reconciliation_edge_type"),
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["reconciliation_assessment.id"],
            name=op.f("fk_reconciliation_edge_assessment_id_reconciliation_assessment"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["supporting_reference_id"],
            ["research_reference.id"],
            name=op.f("fk_reconciliation_edge_supporting_reference_id_research_reference"),
        ),
        sa.ForeignKeyConstraint(
            ["target_source_record_id", "target_content_hash"],
            ["source_record_revision.source_record_id", "source_record_revision.content_hash"],
            name=op.f("fk_reconciliation_edge_target_source_record_id_source_record_revision"),
        ),
        sa.ForeignKeyConstraint(
            ["target_specimen_id", "target_source_record_id"],
            ["specimen_evidence.specimen_id", "specimen_evidence.source_record_id"],
            name=op.f("fk_reconciliation_edge_target_specimen_id_specimen_evidence"),
            deferrable=True,
            initially="DEFERRED",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reconciliation_edge")),
        sa.UniqueConstraint(
            "assessment_id",
            "target_specimen_id",
            "target_source_record_id",
            "target_content_hash",
            name="uq_reconciliation_edge_proof",
        ),
    )
    op.create_index(
        op.f("ix_reconciliation_edge_assessment_id"),
        "reconciliation_edge",
        ["assessment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reconciliation_edge_target_source_record_id"),
        "reconciliation_edge",
        ["target_source_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reconciliation_edge_target_specimen_id"),
        "reconciliation_edge",
        ["target_specimen_id"],
        unique=False,
    )
    op.create_table(
        "reconciliation_review",
        sa.Column("edge_id", sa.Uuid(), nullable=False),
        sa.Column("decision", sa.Text(), nullable=False),
        sa.Column("reviewer", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "reviewed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(reviewer) <> '' AND btrim(reason) <> ''",
            name=op.f("ck_reconciliation_review_provenance"),
        ),
        sa.CheckConstraint(
            "decision IN ('accept','reject','unresolved')",
            name=op.f("ck_reconciliation_review_decision"),
        ),
        sa.ForeignKeyConstraint(
            ["edge_id"],
            ["reconciliation_edge.id"],
            name=op.f("fk_reconciliation_review_edge_id_reconciliation_edge"),
        ),
        sa.PrimaryKeyConstraint("edge_id", name=op.f("pk_reconciliation_review")),
    )
    op.create_index(
        "ix_specimen_reconciliation_key",
        "specimen",
        ["institution_code", "catalog_number", "collection_code"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_specimen_reconciliation_key", table_name="specimen")
    op.drop_table("reconciliation_review")
    op.drop_index(
        op.f("ix_reconciliation_edge_target_specimen_id"), table_name="reconciliation_edge"
    )
    op.drop_index(
        op.f("ix_reconciliation_edge_target_source_record_id"), table_name="reconciliation_edge"
    )
    op.drop_index(op.f("ix_reconciliation_edge_assessment_id"), table_name="reconciliation_edge")
    op.drop_table("reconciliation_edge")
    op.drop_index(
        op.f("ix_reconciliation_assessment_source_record_id"),
        table_name="reconciliation_assessment",
    )
    op.drop_index("ix_reconciliation_assessment_generation", table_name="reconciliation_assessment")
    op.drop_table("reconciliation_assessment")
    op.drop_table("reconciliation_generation")
    # ### end Alembic commands ###
