"""versioned occurrence product browse

Revision ID: 0012_product_browse
Revises: 0011_reconciliation
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0012_product_browse"
down_revision: str | Sequence[str] | None = "0011_reconciliation"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    for table in ("source_normalization_current", "source_record_dependency"):
        op.execute(f"""CREATE TRIGGER invalidate_browse_summaries
            AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON {table}
            FOR EACH STATEMENT EXECUTE FUNCTION invalidate_browse_summaries()""")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "occurrence_browse_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("built_revision", sa.BigInteger(), nullable=False),
        sa.Column("projection_version", sa.Text(), nullable=False),
        sa.Column(
            "built_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint("id = 1", name=op.f("ck_occurrence_browse_state_singleton")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_occurrence_browse_state")),
    )
    op.create_table(
        "occurrence_browse_member",
        sa.Column("occurrence_id", sa.Uuid(), nullable=False),
        sa.Column("source_record_id", sa.Uuid(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("normalization_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["occurrence_id"],
            ["catalog_entry.occurrence_id"],
            name=op.f("fk_occurrence_browse_member_occurrence_id_catalog_entry"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_record_id", "content_hash", "normalization_hash"],
            [
                "normalized_source_revision.source_record_id",
                "normalized_source_revision.content_hash",
                "normalized_source_revision.normalization_hash",
            ],
            name=op.f("fk_occurrence_browse_member_source_record_id_normalized_source_revision"),
        ),
        sa.PrimaryKeyConstraint("occurrence_id", name=op.f("pk_occurrence_browse_member")),
    )
    op.create_index(
        "ix_catalog_occurrence_product_page",
        "catalog_entry",
        ["occurrence_id"],
        unique=False,
        postgresql_include=[
            "source_record_id",
            "content_hash",
            "normalization_hash",
            "policy_version",
        ],
        postgresql_where=sa.text("evidence_kind='occurrence'"),
    )
    op.create_index(
        "ix_identification_reference_occurrence",
        "identification_evidence",
        ["reference_id", "occurrence_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    for table in ("source_normalization_current", "source_record_dependency"):
        op.execute(f"DROP TRIGGER invalidate_browse_summaries ON {table}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_identification_reference_occurrence", table_name="identification_evidence")
    op.drop_index(
        "ix_catalog_occurrence_product_page",
        table_name="catalog_entry",
        postgresql_include=[
            "source_record_id",
            "content_hash",
            "normalization_hash",
            "policy_version",
        ],
        postgresql_where=sa.text("evidence_kind='occurrence'"),
    )
    op.drop_table("occurrence_browse_member")
    op.drop_table("occurrence_browse_state")
    # ### end Alembic commands ###
